apiVersion: apps/v1beta1
kind: Deployment
metadata:
  namespace: kube-gitserver
  name: kube-gitserver-v0
spec:
  replicas: 1
  revisionHistoryLimit: 2
  template: # create pods using pod definition in this template
    metadata:
      labels:
        app: kube-gitserver
        version: v0
        kubernetes.io/cluster-service: "true"
    spec:
      containers:
      - name: gitserver
        image: jkarlos/git-server-docker
        volumeMounts:
        - name: repos
          mountPath: /git-server/repos
        - name: keys
          mountPath: /git-server/keys
        ports:
        - containerPort: 22
          name: gitserver
          protocol: TCP
      volumes:
      - name: repos
        hostPath:
          path: /root/knative/setup/gitserver/repos
      - name: keys
        hostPath:
          path: /root/knative/setup/gitserver/keys
---
apiVersion: v1
kind: Service
metadata:
  name: kube-gitserver
  namespace: kube-gitserver
  labels:
    app: kube-gitserver
spec:
  selector:
    app: kube-gitserver
  type: NodePort
  ports:
  - name: gitserver
    port: 22
    protocol: TCP
    nodePort: 30522
---
apiVersion: v1
kind: Service
metadata:
  name: internal-server
  namespace: kube-gitserver
  labels:
    app: kube-gitserver
spec:
  selector:
    app: kube-gitserver
  type: ClusterIP
  ports:
  - name: gitserver
    port: 22
    protocol: TCP

